Add basic epi model
j-idea/daedalus pull request #7
Opened 2024-07-10 15:14 UTC by pratikunterwegs

This draft PR is WIP adding a basic epi model function.

2024-07-11 17:26 UTC, richfitz requested changes
Apologies for the long sprawling review, but there's a lot of different decisions here that I felt like I could comment on.  Usually we aim to only do one round of review per PR but I imagine this might take a little back and forth.

How similar is this model to the model they have? Aside from the triggers (and the economic model) what other epi bits are missing?

2024-07-11 17:26 UTC, richfitz commented on R/parameters.R
> +  user_params[!names(user_params) %in% names(params)] <- NULL
Always worth thinking about what you want to do about a user-provided parameter `omga`  - here we silently remove it but we might error if unknown parameters are provided?

2024-07-11 17:26 UTC, richfitz commented on _pkgdown.yml
> +  - title: Model function
I'm sure this will change as the package grows, but one section per function just means that you restate the title in two places in the final pkgdown site - you could leave them all in one section at this point perhaps until a structure emerges?

2024-07-11 17:26 UTC, richfitz commented on tests/testthat/_snaps/prepare_output.md
> +# prepare_output: basic expectations
I've never got on with testthat's snapshot testing the various times I've tried to use it, will be interesting to see how this goes

2024-07-11 17:26 UTC, richfitz commented on tests/testthat/_snaps/prepare_output.md
> +      26    2       0-4 infect_asymp 2.655695e-01
Seeing these here makes me think about what the naming strategy will be; there's always a tension between abbreviating for conciseness and predictability (which variables are abbreviated and which aren't).  Here we have two abbreviated and five not. No good solutions here, just an observation and something to think about and/or discuss with the science side

2024-07-11 17:26 UTC, richfitz commented on tests/testthat/test-daedalus.R
> +polymod <- socialmixr::polymod
Can you move the top-level setup code into a test helper (the helper-xxx.R pattern still works in testthat), perhaps a function that returns a list of inputs for this test scenario.  We'll definitely accumulate others over time.

2024-07-11 17:26 UTC, richfitz commented on tests/testthat/test-daedalus.R
> +  expect_true(all(output >= 0.0))
Other tests that might be worth adding here would be: S decreases monotonically, R and dead only increase, etc. Having a few good ideas of epidemiological tests will help the science side write their own tests that test actual behaviours of the model over time.  I can show you tests Ed wrote for the covid model at some point

2024-07-11 17:26 UTC, richfitz requested changes
Apologies for the long sprawling review, but there's a lot of different decisions here that I felt like I could comment on.  Usually we aim to only do one round of review per PR but I imagine this might take a little back and forth.

How similar is this model to the model they have? Aside from the triggers (and the economic model) what other epi bits are missing?

2024-07-12 09:20 UTC, pratikunterwegs commented on NAMESPACE
> +export(daedalus)
I imagine researchers might want to use the package directly rather than via the web app. Agreed the function names don't belong together, but I expect that all function names will change, possibly several times, before the namespace stabilises - currently they're convenience functions for use during development.

I like the idea of being able to call `daedalus::daedalus()` as the main function from this package, but don't mind changing it to `run_daedalus()` or similar.

2024-07-12 09:21 UTC, pratikunterwegs commented on NEWS.md
> +This patch version adds a basic epidemiological model (#7).
Sure - I think it's worth updating the changelog frequently, but I can cut down on the versioning and stick updates between releases under a development heading.

2024-07-12 09:28 UTC, pratikunterwegs commented on R/daedalus.R
> +  # check the initial state matrix for a hardocded number of age groups
> replace these comments with references to the hardcoded values as variables perhaps. If 4 is the number of age groups (is it?) then a constant somewhere in the package would make this easier to read and the comments redundant.

Yes, it's the number of age groups, I can add that as a package constant.

> We're in the process of moving things to use cli errors

Sure, sounds good. I like {cli} and its features generally.

2024-07-12 09:31 UTC, pratikunterwegs commented on R/ode.R
> +.daedalus_ode <- function(t, state, parameters) {
Sure, I can change these. I think using a visible marker for internal functions flags potentially complex code for future developers or users looking under the hood.

2024-07-12 09:37 UTC, pratikunterwegs commented on R/ode.R
> +  new_infections <- beta * state[, 1L, ] *
That's fair - would it be better to collect the compartmental indices along with other constants to a separate `constants.R` file?

>  If you want to try and use the variable packing abstraction I mentioned the other day I can pull together a standalone bit of code for that (should just be 10 or so lines).

Sure, that sounds useful - maybe as a GH gist or similar?

2024-07-12 09:41 UTC, pratikunterwegs commented on R/parameters.R
> +  user_params[!names(user_params) %in% names(params)] <- NULL
I can add more checks on this function. I can add an error on this for unknown parameters, but since these will be silently removed, there's less risk of causing a downstream failure - perhaps a warning instead?

2024-07-12 09:44 UTC, pratikunterwegs commented on R/parameters.R
> +    omega = 1.0 / 100.0,
I find these rates easier to understand and explain as probabilities - here, 1 / 100 are hospitalised or die. I appreciate the parameter list will likely be populated via a workflow in real-world usage and so having interpretable values will be less important.

2024-07-12 09:49 UTC, pratikunterwegs commented on R/prepare_output.R
> +  times <- unique(output[, "time"])
There's no good reason - I think it's a holdover from when I was transforming the data differently, will remove.

2024-07-12 09:59 UTC, pratikunterwegs commented on R/prepare_output.R
> +  checkmate::assert_class(output, c("deSolve", "matrix"))
Sure - we haven't really discussed using custom classes, but I think that would be the way to go if users want to run the model and do scenario comparisons in R workflows. Including the metadata would help ensure scenarios are actually comparable.

One issue that's been brought up to me before is how confident users would in working with custom classes, but perhaps that won't be a problem so long as I write adequate methods and document them. I can add a custom in this PR or move it to a subsequent one if the PR is getting too long to review efficiently.

2024-07-12 10:04 UTC, pratikunterwegs commented on tests/testthat/_snaps/prepare_output.md
> +# prepare_output: basic expectations
I've never really had any problems with it, and it's been useful in flagging potential issues with e.g. estimation methods where changes result in quite large deviations that wouldn't be caught by broader tests for type and value ranges. They can be removed if they don't seem very useful in future.

2024-07-12 10:05 UTC, pratikunterwegs commented on tests/testthat/_snaps/prepare_output.md
> +      26    2       0-4 infect_asymp 2.655695e-01
I can ask them if they have any preferences - I don't have any strong feeling on naming strategies.

2024-07-12 10:08 UTC, pratikunterwegs commented on tests/testthat/test-daedalus.R
> +  expect_true(all(output >= 0.0))
Yes, happy to see a template for model tests. I've tried to keep tests to a minimum as the model structure will likely change (see e.g. below with addition of $R \rightarrow S$ transitions) which will throw off some of these expectations.

2024-07-15 12:35 UTC, pratikunterwegs commented on R/daedalus.R
> +  # check the initial state matrix for a hardocded number of age groups
Switched to using {cli} messages in https://github.com/j-idea/daedalus/pull/7/commits/d6b2be2f688ca159efa70ec73975422dc8ea3dfe and https://github.com/j-idea/daedalus/pull/7/commits/6213a24f0e51bd63c7d1238ff27cf79be511491a, although it does mean quite a lot more code that doesn't fit nicely into existing assert frameworks via `stopifnot()` or {checkmate}.

2024-07-15 12:35 UTC, pratikunterwegs commented on R/ode.R
> +.daedalus_ode <- function(t, state, parameters) {
Renamed to `daedalus_rhs()` in https://github.com/j-idea/daedalus/pull/7/commits/9e094dd235b797180320f6a0eb134d1cce985f5c

2024-07-15 12:37 UTC, pratikunterwegs commented on R/daedalus.R
> +  # check the initial state matrix for a hardocded number of age groups
Added package constants in https://github.com/j-idea/daedalus/pull/7/commits/10df1427f6ba0d2e87bd91a6c7f3087220b61e26 - these are in `R/constants.R`; happy to move to another implementation if that's better.

2024-07-15 12:37 UTC, pratikunterwegs commented on R/ode.R
> +    dim = c(n_age_groups, 7L, 1L)
Done in https://github.com/j-idea/daedalus/pull/7/commits/10df1427f6ba0d2e87bd91a6c7f3087220b61e26

2024-07-15 12:38 UTC, pratikunterwegs commented on R/ode.R
> +  new_infections <- beta * state[, 1L, ] *
I've rolled the compartment indices into the `epi_constants` in https://github.com/j-idea/daedalus/pull/7/commits/10df1427f6ba0d2e87bd91a6c7f3087220b61e26

2024-07-15 12:41 UTC, pratikunterwegs commented on R/parameters.R
> +  params <- utils::modifyList(params, user_params)
There's the potential for some `NULL`s to be carried between lists, but it doesn't seem too likely here. I've switched to the manual replacement in https://github.com/j-idea/daedalus/pull/7/commits/d6b2be2f688ca159efa70ec73975422dc8ea3dfe

2024-07-15 12:42 UTC, pratikunterwegs commented on R/parameters.R
> +  user_params[!names(user_params) %in% names(params)] <- NULL
I've added a warning rather than an error on extra parameters in https://github.com/j-idea/daedalus/pull/7/commits/d6b2be2f688ca159efa70ec73975422dc8ea3dfe

2024-07-15 12:43 UTC, pratikunterwegs commented on R/prepare_output.R
> +  times <- unique(output[, "time"])
Fixed in https://github.com/j-idea/daedalus/pull/7/commits/2dd4bfd9290a4aaf80d3bc12a2af2e7062dde0a1

2024-07-15 12:44 UTC, pratikunterwegs commented on R/prepare_output.R
> +  checkmate::assert_class(output, c("deSolve", "matrix"))
I haven't implemented a custom class for the output although I agree this would probably be the way to go in the near future in a separate PR. My suggestion is to add this in the PR after the basic economic model goes in, so still perhaps 2 -- 3 PRs down the line.

2024-07-15 12:47 UTC, pratikunterwegs commented on R/prepare_output.R
> +    value = c(output[, -1L])
Fixed in https://github.com/j-idea/daedalus/pull/7/commits/2dd4bfd9290a4aaf80d3bc12a2af2e7062dde0a1

2024-07-15 12:50 UTC, pratikunterwegs commented on README.Rmd
> +data <- prepare_output(output)
I haven't changed the name in this PR but only because the name will probably change a few more times and it might be good to get feedback from EPPI on whether they are even interested in the timeseries data or whether they're only after the costs, in which case this could be removed or it could become an internal function.

2024-07-15 12:53 UTC, pratikunterwegs commented on R/daedalus.R
> +daedalus <- function(initial_state, time_end = 100L,
I think users will only rarely want to change the end time as they're probably going to want to compare outcomes (cases, deaths, costs) over identical timescales in different scenarios. The EPPI folks have mentioned a standard comparison period of 300 days, so I've set that as the default (changed from 100, which is related to the CEPI 100 days mission). 300 days sounds about right as that gives more time for the effect of interventions to play out as well.

2024-07-15 12:54 UTC, pratikunterwegs commented on README.Rmd
> +)
Updated in https://github.com/j-idea/daedalus/pull/7/commits/d5cfb6eddb364e7e638555c60032661ebd06648f

2024-07-15 12:54 UTC, pratikunterwegs commented on _pkgdown.yml
> +  - title: Model function
I've rolled back to a single reference section for all functions now: https://github.com/j-idea/daedalus/pull/7/commits/170fe6ed6b6350f2ee8dc40843a98978b84ffbad

2024-07-15 12:56 UTC, pratikunterwegs commented on tests/testthat/_snaps/prepare_output.md
> +      26    2       0-4 infect_asymp 2.655695e-01
I've asked about naming strategies - they're discussing this themselves and we decided this could be parked for now if that's alright.

2024-07-15 12:56 UTC, pratikunterwegs commented on tests/testthat/test-daedalus.R
> +polymod <- socialmixr::polymod
Moved setup code to `tests/testthat/helper-daedalus.R

2024-07-15 13:31 UTC, richfitz approved these changes
Thanks - let's get this merged, all the outstanding items look fine to defer until later (as you've noted in comments already). Looks like a good starting point!

2024-07-15 13:32 UTC, merged